module h0_1_upstream_cluster_shell (
  input  logic        clk_i,
  input  logic        rst_ni,

  input  logic        host_r_ready_i,
  input  logic        host_ar_valid_i,
  input  logic [31:0] host_ar_addr_i,
  input  logic [2:0]  host_ar_size_i,
  input  logic [1:0]  host_ar_id_i,
  output logic        host_ar_ready_o,
  output logic        host_r_valid_o,
  output logic [63:0] host_r_data_o,
  output logic [1:0]  host_r_resp_o,
  output logic [1:0]  host_r_id_o,
  output logic        host_r_last_o,

  input  logic        host_b_ready_i,
  input  logic        host_aw_valid_i,
  input  logic [31:0] host_aw_addr_i,
  input  logic [2:0]  host_aw_size_i,
  input  logic [1:0]  host_aw_id_i,
  output logic        host_aw_ready_o,
  input  logic        host_w_valid_i,
  input  logic [63:0] host_w_data_i,
  input  logic [7:0]  host_w_strb_i,
  input  logic        host_w_last_i,
  output logic        host_w_ready_o,
  output logic        host_b_valid_o,
  output logic [1:0]  host_b_resp_o,
  output logic [1:0]  host_b_id_o,
  output logic        boot_fetch_seen_o
);
  logic wide_out_r_ready, wide_out_ar_valid;
  logic [31:0] wide_out_ar_addr;
  logic [7:0] wide_out_ar_len;
  logic [2:0] wide_out_ar_size;
  logic [1:0] wide_out_ar_burst;
  logic [2:0] wide_out_ar_id;
  logic boot_r_valid, boot_r_last, boot_ar_ready;
  logic [63:0] boot_r_data;
  logic [1:0] boot_r_resp;
  logic [2:0] boot_r_id;

  axi_boot_rom #(.IdWidth(3)) i_boot_rom (
    .clk_i(clk_i), .rst_ni(rst_ni),
    .ar_valid_i(wide_out_ar_valid), .ar_ready_o(boot_ar_ready),
    .ar_addr_i(wide_out_ar_addr), .ar_len_i(wide_out_ar_len),
    .ar_size_i(wide_out_ar_size), .ar_burst_i(wide_out_ar_burst),
    .ar_id_i(wide_out_ar_id), .r_valid_o(boot_r_valid),
    .r_ready_i(wide_out_r_ready), .r_data_o(boot_r_data),
    .r_resp_o(boot_r_resp), .r_last_o(boot_r_last), .r_id_o(boot_r_id),
    .fetch_seen_o(boot_fetch_seen_o)
  );

  de1_u3_snitch_cluster_wrapper i_cluster (
    .clk_i                         (clk_i),
    .rst_ni                        (rst_ni),
    .meip_i                        ('0),
    .mtip_i                        ('0),
    .msip_i                        ('0),

    .narrow_in_req_i_r_ready       (host_r_ready_i),
    .narrow_in_req_i_ar_valid      (host_ar_valid_i),
    .narrow_in_req_i_ar_user       ('0),
    .narrow_in_req_i_ar_region     ('0),
    .narrow_in_req_i_ar_qos        ('0),
    .narrow_in_req_i_ar_prot       ('0),
    .narrow_in_req_i_ar_cache      ('0),
    .narrow_in_req_i_ar_lock       ('0),
    .narrow_in_req_i_ar_burst      (2'b01),
    .narrow_in_req_i_ar_size       (host_ar_size_i),
    .narrow_in_req_i_ar_len        ('0),
    .narrow_in_req_i_ar_addr       (host_ar_addr_i),
    .narrow_in_req_i_ar_id         (host_ar_id_i),
    .narrow_in_req_i_b_ready       (host_b_ready_i),
    .narrow_in_req_i_w_valid       (host_w_valid_i),
    .narrow_in_req_i_w_user        ('0),
    .narrow_in_req_i_w_last        (host_w_last_i),
    .narrow_in_req_i_w_strb        (host_w_strb_i),
    .narrow_in_req_i_w_data        (host_w_data_i),
    .narrow_in_req_i_aw_valid      (host_aw_valid_i),
    .narrow_in_req_i_aw_user       ('0),
    .narrow_in_req_i_aw_atop       ('0),
    .narrow_in_req_i_aw_region     ('0),
    .narrow_in_req_i_aw_qos        ('0),
    .narrow_in_req_i_aw_prot       ('0),
    .narrow_in_req_i_aw_cache      ('0),
    .narrow_in_req_i_aw_lock       ('0),
    .narrow_in_req_i_aw_burst      (2'b01),
    .narrow_in_req_i_aw_size       (host_aw_size_i),
    .narrow_in_req_i_aw_len        ('0),
    .narrow_in_req_i_aw_addr       (host_aw_addr_i),
    .narrow_in_req_i_aw_id         (host_aw_id_i),
    .narrow_in_resp_o_r_last       (host_r_last_o),
    .narrow_in_resp_o_r_resp       (host_r_resp_o),
    .narrow_in_resp_o_r_data       (host_r_data_o),
    .narrow_in_resp_o_r_id         (host_r_id_o),
    .narrow_in_resp_o_r_valid      (host_r_valid_o),
    .narrow_in_resp_o_b_resp       (host_b_resp_o),
    .narrow_in_resp_o_b_id         (host_b_id_o),
    .narrow_in_resp_o_b_valid      (host_b_valid_o),
    .narrow_in_resp_o_w_ready      (host_w_ready_o),
    .narrow_in_resp_o_ar_ready     (host_ar_ready_o),
    .narrow_in_resp_o_aw_ready     (host_aw_ready_o),

    .narrow_out_resp_i_r_user      ('0),
    .narrow_out_resp_i_r_last      (1'b1),
    .narrow_out_resp_i_r_resp      (2'b11),
    .narrow_out_resp_i_r_data      ('0),
    .narrow_out_resp_i_r_id        ('0),
    .narrow_out_resp_i_r_valid     (1'b0),
    .narrow_out_resp_i_b_user      ('0),
    .narrow_out_resp_i_b_resp      (2'b11),
    .narrow_out_resp_i_b_id        ('0),
    .narrow_out_resp_i_b_valid     (1'b0),
    .narrow_out_resp_i_w_ready     (1'b0),
    .narrow_out_resp_i_ar_ready    (1'b0),
    .narrow_out_resp_i_aw_ready    (1'b0),

    .wide_out_resp_i_r_user        ('0),
    .wide_out_req_o_r_ready        (wide_out_r_ready),
    .wide_out_req_o_ar_valid       (wide_out_ar_valid),
    .wide_out_req_o_ar_addr        (wide_out_ar_addr),
    .wide_out_req_o_ar_len         (wide_out_ar_len),
    .wide_out_req_o_ar_size        (wide_out_ar_size),
    .wide_out_req_o_ar_burst       (wide_out_ar_burst),
    .wide_out_req_o_ar_id          (wide_out_ar_id),
    .wide_out_resp_i_r_last        (boot_r_last),
    .wide_out_resp_i_r_resp        (boot_r_resp),
    .wide_out_resp_i_r_data        (boot_r_data),
    .wide_out_resp_i_r_id          (boot_r_id),
    .wide_out_resp_i_r_valid       (boot_r_valid),
    .wide_out_resp_i_b_user        ('0),
    .wide_out_resp_i_b_resp        (2'b11),
    .wide_out_resp_i_b_id          ('0),
    .wide_out_resp_i_b_valid       (1'b0),
    .wide_out_resp_i_w_ready       (1'b0),
    .wide_out_resp_i_ar_ready      (boot_ar_ready),
    .wide_out_resp_i_aw_ready      (1'b0),

    .wide_in_req_i_r_ready         (1'b0),
    .wide_in_req_i_ar_valid        (1'b0),
    .wide_in_req_i_ar_user         ('0),
    .wide_in_req_i_ar_region       ('0),
    .wide_in_req_i_ar_qos          ('0),
    .wide_in_req_i_ar_prot         ('0),
    .wide_in_req_i_ar_cache        ('0),
    .wide_in_req_i_ar_lock         ('0),
    .wide_in_req_i_ar_burst        ('0),
    .wide_in_req_i_ar_size         ('0),
    .wide_in_req_i_ar_len          ('0),
    .wide_in_req_i_ar_addr         ('0),
    .wide_in_req_i_ar_id           ('0),
    .wide_in_req_i_b_ready         (1'b0),
    .wide_in_req_i_w_valid         (1'b0),
    .wide_in_req_i_w_user          ('0),
    .wide_in_req_i_w_last          (1'b0),
    .wide_in_req_i_w_strb          ('0),
    .wide_in_req_i_w_data          ('0),
    .wide_in_req_i_aw_valid        (1'b0),
    .wide_in_req_i_aw_user         ('0),
    .wide_in_req_i_aw_atop         ('0),
    .wide_in_req_i_aw_region       ('0),
    .wide_in_req_i_aw_qos          ('0),
    .wide_in_req_i_aw_prot         ('0),
    .wide_in_req_i_aw_cache        ('0),
    .wide_in_req_i_aw_lock         ('0),
    .wide_in_req_i_aw_burst        ('0),
    .wide_in_req_i_aw_size         ('0),
    .wide_in_req_i_aw_len          ('0),
    .wide_in_req_i_aw_addr         ('0),
    .wide_in_req_i_aw_id           ('0)
  );
endmodule
