#!/usr/bin/env python3
"""Convert a little-endian RISC-V binary into a checked SystemVerilog ROM."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("binary", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--dump", type=Path, required=True)
    parser.add_argument("--max-words", type=int, default=64)
    parser.add_argument("--prefix", default="s6")
    parser.add_argument("--default-word", default="0x0000006f")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data = args.binary.read_bytes()
    if len(data) == 0:
        raise SystemExit(f"{args.binary} is empty")
    if len(data) % 4 != 0:
        raise SystemExit(f"{args.binary} size {len(data)} is not 4-byte aligned")

    words = [
        int.from_bytes(data[offset : offset + 4], byteorder="little")
        for offset in range(0, len(data), 4)
    ]

    if len(words) > args.max_words:
        raise SystemExit(
            f"ROM image has {len(words)} words, exceeds --max-words {args.max_words}"
        )

    default_word = int(args.default_word, 0)
    digest = hashlib.sha256(data).hexdigest()
    pfx = args.prefix.upper()
    fn = f"{args.prefix}_rom_word"

    lines = [
        "// Generated by scripts/bin_to_rom_svh.py.",
        "// Do not edit by hand; edit the assembly source instead.",
        f"// source: {args.source}",
        f"// words: {len(words)} / {args.max_words}",
        f"// bytes: {len(data)}",
        f"// sha256: {digest}",
        f"localparam int unsigned {pfx}_ROM_WORDS = {len(words)};",
        f"localparam int unsigned {pfx}_ROM_BYTES = {len(data)};",
        f"localparam int unsigned {pfx}_ROM_MAX_WORDS = {args.max_words};",
        "",
        f"function automatic logic [31:0] {fn}(input logic [31:0] word_index);",
        "    unique case (word_index)",
    ]

    for idx, word in enumerate(words):
        lines.append(f"        32'd{idx}: {fn} = 32'h{word:08x};")

    lines.extend(
        [
            f"        default: {fn} = 32'h{default_word:08x};",
            "    endcase",
            "endfunction",
            "",
        ]
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")

    manifest = {
        "source": str(args.source),
        "binary": str(args.binary),
        "dump": str(args.dump),
        "rom_svh": str(args.output),
        "bytes": len(data),
        "words": len(words),
        "max_words": args.max_words,
        "sha256": digest,
        "default_word": f"0x{default_word:08x}",
        "words_hex": [f"0x{word:08x}" for word in words],
    }
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
