// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul  9 2026 16:12:30 -03 (Jul  9 2026 19:12:30 UTC)
//
// Source design: toy_counter
// Target library: TSMC65 tcbn65lp_200a/tcbn65lptc.lib

module toy_counter(clk_i, rst_ni, en_i, count_o);
  input clk_i, rst_ni, en_i;
  output [7:0] count_o;
  wire clk_i, rst_ni, en_i;
  wire [7:0] count_o;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  SDFCNQD1 \count_o_reg[7] (.CDN (rst_ni), .CP (clk_i), .D
       (count_o[7]), .SI (n_13), .SE (en_i), .Q (count_o[7]));
  SDFCNQD1 \count_o_reg[6] (.CDN (rst_ni), .CP (clk_i), .D
       (count_o[6]), .SI (n_11), .SE (en_i), .Q (count_o[6]));
  SDFCNQD1 \count_o_reg[5] (.CDN (rst_ni), .CP (clk_i), .D
       (count_o[5]), .SI (n_9), .SE (en_i), .Q (count_o[5]));
  MOAI22D0 g185__2398(.A1 (n_12), .A2 (count_o[7]), .B1 (n_12), .B2
       (count_o[7]), .ZN (n_13));
  OA21D0 g187__5107(.A1 (n_10), .A2 (count_o[6]), .B (n_12), .Z (n_11));
  SDFCNQD1 \count_o_reg[4] (.CDN (rst_ni), .CP (clk_i), .D
       (count_o[4]), .SI (n_7), .SE (en_i), .Q (count_o[4]));
  CKND2D0 g188__6260(.A1 (n_10), .A2 (count_o[6]), .ZN (n_12));
  IAO21D0 g190__4319(.A1 (n_8), .A2 (count_o[5]), .B (n_10), .ZN (n_9));
  SDFCNQD1 \count_o_reg[3] (.CDN (rst_ni), .CP (clk_i), .D
       (count_o[3]), .SI (n_5), .SE (en_i), .Q (count_o[3]));
  CKAN2D1 g191__8428(.A1 (n_8), .A2 (count_o[5]), .Z (n_10));
  IAO21D0 g193__5526(.A1 (n_6), .A2 (count_o[4]), .B (n_8), .ZN (n_7));
  SDFCNQD1 \count_o_reg[2] (.CDN (rst_ni), .CP (clk_i), .D
       (count_o[2]), .SI (n_3), .SE (en_i), .Q (count_o[2]));
  CKAN2D1 g194__6783(.A1 (n_6), .A2 (count_o[4]), .Z (n_8));
  IAO21D0 g196__3680(.A1 (n_4), .A2 (count_o[3]), .B (n_6), .ZN (n_5));
  SDFCNQD1 \count_o_reg[1] (.CDN (rst_ni), .CP (clk_i), .D
       (count_o[1]), .SI (n_1), .SE (en_i), .Q (count_o[1]));
  CKAN2D1 g197__1617(.A1 (n_4), .A2 (count_o[3]), .Z (n_6));
  IAO21D0 g199__2802(.A1 (n_2), .A2 (count_o[2]), .B (n_4), .ZN (n_3));
  SDFCNQD1 \count_o_reg[0] (.CDN (rst_ni), .CP (clk_i), .D (en_i), .SI
       (n_0), .SE (count_o[0]), .Q (count_o[0]));
  CKAN2D1 g200__1705(.A1 (n_2), .A2 (count_o[2]), .Z (n_4));
  IAO21D0 g202__5122(.A1 (count_o[0]), .A2 (count_o[1]), .B (n_2), .ZN
       (n_1));
  CKAN2D1 g203__8246(.A1 (count_o[1]), .A2 (count_o[0]), .Z (n_2));
  CKND0 g204(.I (en_i), .ZN (n_0));
endmodule
