#!/usr/bin/env python3
"""Convert a little-endian RISC-V binary into a SystemVerilog ROM function."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("binary", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--default-word", default="0x0000006f")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data = args.binary.read_bytes()
    if len(data) == 0:
        raise SystemExit(f"{args.binary} is empty")
    if len(data) % 4 != 0:
        raise SystemExit(f"{args.binary} size is not 4-byte aligned")

    words = [
        int.from_bytes(data[offset : offset + 4], byteorder="little")
        for offset in range(0, len(data), 4)
    ]
    default_word = int(args.default_word, 0)

    lines = [
        "// Generated by scripts/bin_to_rom_svh.py.",
        "// Do not edit by hand; edit sw/led_mmio.S instead.",
        f"localparam int unsigned S5_ROM_WORDS = {len(words)};",
        "",
        "function automatic logic [31:0] s5_rom_word(input logic [31:0] word_index);",
        "    unique case (word_index)",
    ]

    for idx, word in enumerate(words):
        lines.append(f"        32'd{idx}: s5_rom_word = 32'h{word:08x};")

    lines.extend(
        [
            f"        default: s5_rom_word = 32'h{default_word:08x};",
            "    endcase",
            "endfunction",
            "",
        ]
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
